import time
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen
def stonks(x='LSE',y='UK',z = '0'):
    time.sleep(z)
    dict1 = {'UK':{'FTSE100':'https://uk.investing.com/indices/uk-100','WTB':'https://uk.investing.com/equities/whitbread','GSK':'https://uk.investing.com/equities/glaxosmithkline','RR':'https://uk.investing.com/equities/rolls-royce','LLOY':'https://uk.investing.com/equities/lloyds-banking-grp','EZY':'https://uk.investing.com/equities/easyjet','MRW':'https://uk.investing.com/equities/william-morrison','TSCO':'https://uk.investing.com/equities/tesco','ULVR':'https://uk.investing.com/equities/unilever','BARC':'https://uk.investing.com/equities/barclays','AZN':'https://uk.investing.com/equities/astrazeneca','BVIC':'https://uk.investing.com/equities/britvic','BT':'https://uk.investing.com/equities/bt-group','MKS':'https://uk.investing.com/equities/marks---spencer-group','SBRY':'https://uk.investing.com/equities/sainsbury','GRG':'https://uk.investing.com/equities/greggs','UU':'https://uk.investing.com/equities/united-utilities','IAG':'https://uk.investing.com/equities/intl.-cons.-air-grp','DOM':'https://uk.investing.com/equities/dominos-pizza-ukir','CPG':'https://uk.investing.com/equities/compass-group','LGEN':'https://uk.investing.com/equities/legal---general','DC':'https://uk.investing.com/equities/carphone-warehouse-group','VMUK':'','GDR':'https://www.investing.com/equities/epistem-holdings-plc','NG':'https://www.investing.com/equities/national-grid','OCDO':'https://www.investing.com/equities/ocado-group','ADM':'https://www.investing.com/equities/admiral-group','AO':'https://www.investing.com/equities/ao-world','HIK':'https://www.investing.com/equities/hikma-pharmaceuticals','BATS':'https://www.investing.com/equities/british-american-tobacco','RDSA':'https://www.investing.com/equities/royal-dutch-shell-a-plc','RDSB':'https://www.investing.com/equities/royal-dutch-shell-b-plc','AV':'https://www.investing.com/equities/aviva','DGE':'https://www.investing.com/equities/diageo','TRN':'https://www.investing.com/equities/trainline-plc','RB':'https://www.investing.com/equities/reckitt-benckiser','HFD':'https://www.investing.com/equities/halfords-group','BIFF':'https://www.investing.com/equities/biffa-plc','SGC':'https://www.investing.com/equities/stagecoach-group','DLG':'https://www.investing.com/equities/direct-line?cid=48468','BP':'https://www.investing.com/equities/bp','WIZZ':'https://www.investing.com/equities/wizz-air-holdings-plc','BIDS':'https://www.investing.com/equities/fitbug-holdings-plc','AA':'','SDRY':'https://www.investing.com/equities/supergroup-plc','LSE':'https://www.investing.com/equities/london-stock-exchange','CINE':'https://uk.investing.com/equities/cineworld-group-plc'},
             'USA':{'DOW':'https://uk.investing.com/indices/us-30','SP500':'https://uk.investing.com/indices/us-spx-500','NASDAQ':'https://uk.investing.com/indices/nq-100','AAPL':'https://www.investing.com/equities/apple-computer-inc'},
             'DEU':{'DAX':'https://uk.investing.com/indices/germany-30'}}
    r = Request((dict1[y][x]), headers={"User-Agent": "Chrome/7.0"})
    c = urlopen(r).read()
    soup = BeautifulSoup(c, "html.parser")
    #print(soup)
    final  = (soup.find(id="last_last").string).replace(',','')
    return final
